"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Logout from "./components/logout";
import { useAuthUser } from "@/hooks/auth";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authUser = useAuthUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          {children}
          {authUser && <Logout />}
        </StoreProvider>
      </body>
    </html>
  );
}
